# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [AA, Ghost]
patreon: # Replace with a single Patreon username mouse36872
open_collective: # Replace with a single Open Collective username shapeshift.io
ko_fi: # Replace with a single Ko-fi username mouse3687
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., slack-foundry
liberapay: # Replace with a single Liberapay username mouse3687
issuehunt: # Replace with a single IssueHunt username mouse3687
otechie: # Replace with a single Otechie username mouse3687
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://amvets.org','https://opensea.io','https://rolex.com','https://wikileaks.com','https://pornhub.com','https://kllm.com','https://magnoliaelectric.com']
